"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import dynamic from "next/dynamic";
import { Toaster } from "sonner";
// import useAlan from "@/hooks/useAlan";
import { LocalizationProvider } from "@sujalchoudhari/localization";
import { Chatbot } from "@/components/ChatBot";

const SideBar = dynamic(() => import("@/components/sidebar/SideBar"), {
  ssr: false,
});

const NavBar = dynamic(() => import("@/components/NavBar"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // useAlan();
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LocalizationProvider>
                <Toaster />
                <div className="overflow-hidden flex min-h-screen min-w-screen bg-themebackground">
                  <SideBar />
                  <div className="flex flex-col flex-1 h-screen items-center overflow-y-auto">
                    <header className="sticky top-0 w-full !pl-[0.8rem] !pr-[0.8rem] md:!pl-[1.5rem] md:!pr-[1.5rem] z-10 flex justify-center">
                      <NavBar />
                    </header>
                    <main className="flex-1 max-w-[1440px] w-full pl-[0.8rem] pr-[0.8rem] md:!pl-[1.5rem] md:pr-[1.5rem]">
                      <Chatbot />
                      {children}
                    </main>
                  </div>
                </div>
            </LocalizationProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
